#!/bin/sh
# inkVerb repo knight, verb.ink

# This installs the Root Certificate Authority files to the "inkcert" folder on a USB on your local machine, then symlinks them to your local machine's /etc/inkcert/root directory
## This is to be done on a local machine not currently connected to the Internet!
## If the inkcert folder does not exist on your USB, it will automatically be tested and created
## Prereq: Verber inkcertinstall (yes, on your local computer)
## Prereq: Your inkCert CA USB is plugged in and mounted

# How to use:
## ./installcaroot [/full/path/to/mounted/usb]

# Eg:
## ./installcaroot /media/user/USB


ROOTCAPATH=$1

# Prepare directories
cd /${ROOTCAPATH}
if [ ! -d "inkcert" ]; then
mkdir inkcert
fi
cd inkcert
mkdir ca
cd ca
mkdir ca-certs root req
cd /${ROOTCAPATH}/inkcert/ca/root
mkdir certs crl newcerts private pf
chmod 700 root/private
chmod 700 req
mkdir -p /etc/inkcert
ln -s /${ROOTCAPATH}/inkcert/ca /etc/inkcert/

# Important files
touch root/index.txt
echo 1000 > serial
cp /var/local/inkcert/conflab/ca/root-openssl.cnf /etc/inkcert/ca/root/openssl.cnf

# Remove the symlink
cd ~
rm /etc/inkcert/ca

# Finish
echo "Excellent!

Now, you can run newcarootkeys, then download and sign the Intermediate csr.
"

