#!/bin/sh
# inkVerb repo knight, verb.ink

# This signs the inkCert Authority Interm csr on a USB that already has inscallcaroot run for it
## This is to be done on a local machine!
## Prereq: Inker - inkcertintermcsr
## Prereq: the interm csr must be on the mounted USB at USB/inkcert/ca/req/interm/intermediate.csr.pem

# Thanks Jamie Nguyen! https://jamielinux.com/
## https://jamielinux.com/docs/openssl-certificate-authority/
# Changes
# /root/ca - /etc/inkcert/ca
# ca.key.pem - ca.inkcert.key.pem
# ca.cert.pem - ca.inkcert.cert.pem
# intermediate.key.pem - interm.inkcert.key.pem
# intermediate.cert.pem - interm.inkcert.cert.pem

# How to use:
## ./signintermcsr [/full/path/to/mounted/usb]
# Eg:
## ./installcaroot /media/user/USB


ROOTCAPATH=$1

# inkCert root symlink
if [ ! -d "/etc/inkcert/ca" ]; then
rm /etc/inkcert/ca
fi
ln -s /${ROOTCAPATH}/inkcert/ca /etc/inkcert/

# Sign the csr for the cert
## NOTE: specify the root ca file
cd /etc/inkcert/ca
mkdir req/interm
fi
openssl ca -config openssl.cnf -extensions v3_intermediate_ca \
	-days 375 -notext -md sha256 \
	-in req/interm/intermediate.csr.pem \
	-out req/interm/interm.inkcert.cert.pem \
	-passin pass:root/pf/pcafraez
###INTERACT Enter pass phrase for ca.inkcert.key.pem: secretpassword
###INTERACT Sign the certificate? [y/n]: y
chmod 444 req/interm.inkcert.cert.pem
## Make the backup
timestamp=`date '+%Y_%m_%d__%H_%M_%S'`;
cp /etc/inkcert/ca/req/interm/interm.inkcert.cert.pem /etc/inkcert/ca/req/interm/interm.inkcert.vbak_$timestamp.cert.pem

# Output to check
openssl x509 -noout -text \
	-in req/interm/interm.inkcert.cert.pem
read -p "Verify, then press [Enter] to continue to create the interm chain file, or Ctrl+C to cancel now..."
###INTERACT

# Zip
cp root/certs/ca.inkcert.cert.pem req/interm/
cp root/certs/interm.inkcert.vbak_$timestamp.cert.pem req/interm/
cd req
zip -r interm.zip interm
rm -R interm

# Remove the symlink
cd ~
rm /etc/inkcert/ca

# Finish
echo "Foil's off the bottle, Cap'n.

Ready the goblets. Now you need to upload USB/inkcert/req/interm.zip to your inkCert Intermediate CA server in /etc/inkcert/ca/req/ (or linked ~/ink/req or ~/boss/req), then run the addintermcert knight...
"

